### ISSUE TITLE
add context help for UI elements - filter controls

### ISSUE THREAD

**Issue by michaelbrooks** [etcgroup/agave#28]
Any non-obvious aspects of the tool (and there are many) should have a way to obtain an explanation. This could be either a (?) icon that displays a small box on hover, a tooltip, or something you have to click. Depends on the context.

**Comment by michaelbrooks** [comment]
List of items needing labels [here](https://docs.google.com/a/uw.edu/document/d/16rmQeEigaNp-TMSa8mYy5kciCt3W4vsjm8g5kdeuwX0/edit).

Added some in a77c9534e9888dc96226c3dc2291ed64740b2955, 620dbe4275bf75f7f97643179ea812e44f765a55, and e832957fd1c5529f3ba513ac4c6f7f61c82a3b80.

**Comment by michaelbrooks** [comment]
This issue is now about improving the usability of the filter controls.

**Comment by mtork** [comment]
Fixed in 864ac3ced4f245955e211e6930cfb17a2e9b9358 0645b677be70da1d1f9d0fab6eeb787674231306 82a7bce97b8b3a94c1e4ed2ca4f992a9a7eb358e
