### ISSUE TITLE
add zoom to tweet/time

### ISSUE THREAD

**Issue by michaelbrooks** [etcgroup/agave#38]
When you click on a tweet you should be able to go to it somehow.

**Comment by michaelbrooks** [comment]
Instead of zooming to the time in question, maybe double-click on the focus chart should zoom in?
Seems like it would be confusing and disruptive to move the view when you click a tweet. Although if it were
based on clicking a zoom button, that could work.

**Comment by michaelbrooks** [comment]
Ok, here's what we need to do:
- anybody that sends a brush event for tweets should also attach the tweet data
- timeline doesn't listen for tweets, no tweet cache. on tweet brush events, use the data attached to the event.
- when comments are downloaded, tweet data for referenced tweets needs to be included

**Comment by michaelbrooks** [comment]
@geosoco I'm redoing some of the front-end code for this, by the way. It came up as I was working on brushing keywords.

**Comment by michaelbrooks** [comment]
Partly complete in 94488b44525e2486daa43951ff102bed6f19584c

**Comment by geosoco** [comment]
This should be complete now.
