### ISSUE TITLE
use d3.area.defined to hide zero data in expanded mode

### ISSUE THREAD

**Issue by michaelbrooks** [etcgroup/agave#63]
Just found this: https://github.com/mbostock/d3/wiki/SVG-Shapes#wiki-area_defined

We can use it to hide the expanded area plot when there are zero tweets in an interval. The line and non-expanded area plots should be unaffected because they represent zero values well anyway.

**Comment by mtork** [comment]
Fixed in 158eb3a7016c55ea3cc77b79da2b0a8e182f8e58
